language: scala
scala:
    - 2.10.5
    - 2.11.6
jdk:
    - oraclejdk8
    - oraclejdk7
    - openjdk7
env:
    # Split build between unit and integration tests
    matrix:
        - TEST_SUITE=test EXTRA_SBT_OPT=-J-XX:ReservedCodeCacheSize=256M
        - TEST_SUITE=it:test EXTRA_SBT_OPT=-J-XX:ReservedCodeCacheSize=256M
script:
    # Run our test for a specific Scala version and specific test suite
    - sbt ++$TRAVIS_SCALA_VERSION $EXTRA_SBT_OPT "$TEST_SUITE"
after_script:
    # Avoid unnecessary cache updates
    - find $HOME/.sbt -name "*.lock" | xargs rm
    - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm
sudo: false
cache:
    directories:
        - $HOME/.ivy2/cache
        - $HOME/.sbt/boot
notifications:
    webhooks:
        urls:
            - WEB_URL
        on_success: change  # options: [always|never|change] default: always
        on_failure: always  # options: [always|never|change] default: always
        on_start: false     # default: false

